# BoardConfig.mk for ireadygo G2 (MT6589)
# Cleaned for CWM/PhilZ Touch compatibility

LOCAL_PATH := device/ireadygo/G2

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_BOARD_PLATFORM := mt6589

# Kernel
TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/prebuilt/zImage-dtb
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 20971520
BOARD_HAS_NO_SELECT_BUTTON := false

# SELinux (disable for old devices)
SELINUX_IGNORE_NEVERALLOWS := true
BOARD_USES_SEPOLICY := false

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x01000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x20000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x18000000
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x0a000000
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

# CWM specific flags (optional)
BOARD_USE_CUSTOM_RECOVERY_FONT := \"font_10x18.h\"
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_SUPPRESS_EMMC_WIPE := true
